[package]
name = "nn_slave"
version.workspace = true
authors = ["Maxim Shalagin <shalaginx998@yandex.ru>"]
description = "Fuzzer with neural network inside"
repository = "https://git.mobiledep.ru/iifuzzing/nn_fuzz/"
readme = "../README.md"
license = "MIT OR Apache-2.0"
keywords = ["fuzzing", "testing", "security"]
edition = "2021"
categories = ["development-tools::testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
observer_feedback = []
tui = []
bind_public = []

[dependencies]
libafl = { path = "../../LibAFL/libafl", features = [] }
libafl_cc = { path = "../../LibAFL/libafl_cc", features = [] }


# libc = {registry = "stc", version = "*"}
# tok = {registry = "stc", package = "tokio", version = "*"}
# ds =  {package = "polars", version = "*"}