stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
    - linux
  image: registry2.mobiledep.ru/scan_r12-quay.io/pypa/manylinux2014_x86_64
  script:
    - curl --proto '=https' --tlsv1.3 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
    - source "$HOME/.cargo/env"
    - rm -rf ../LibAFL
    - git clone --branch develop https://$DEPLOY_USER:$DEPLOY_TOKEN@git.mobiledep.ru/iifuzzing/libafl ../LibAFL
    - ls -la
    - cargo build --release 
    - mkdir -p ./artifacts && cp -r ./target/release/libnn_* ./target/release/nn_* ./artifacts
    - python3.8 -m pip install -i ${SWS_PYPI_INDEX} --trusted-host ${SWS_PYPI_HOST} -U pip
    - python3.8 -m pip install -i ${SWS_PYPI_INDEX} --trusted-host ${SWS_PYPI_HOST} -U maturin
    - cd nn_connector
    - python3.8 -m maturin publish --repository-url ${SWS_PYPI_HOSTED} -u ${SWS_PYPI_USER} -p ${SWS_PYPI_PASSW} --no-sdist --compatibility manylinux2014
  artifacts:
    paths:
      - artifacts/
    expire_in: 10 min
  only:
    - tags

deploy:
  stage: deploy
  tags:
    - docker
    - linux
  image: registry2.mobiledep.ru/scan_r12-hub.docker.com/library/alpine:latest
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --no-cache --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $SERVER_USER@$SERVER_HOST "rm -rf /tmp/*"
  - scp -r ./artifacts $SERVER_USER@$SERVER_HOST:/tmp/
  only:
  - tags
  needs:
  - build