[package]
name = "nn_fuzz"
version = "0.1.0"
authors = ["Maxim Shalagin <shalaginx998@yandex.ru>"]
description = "Fuzzer for executables with neural network backend"
repository = "https://git.mobiledep.ru/iifuzzing/nn_fuzz/"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["fuzzing", "testing", "security"]
edition = "2021"
categories = ["development-tools::testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
tui = []
bind_public = []

[profile.release]
lto = true
opt-level = 3

[dependencies]
libafl = { path = "../LibAFL/libafl", features = [] }
libafl_cc = { path = "../LibAFL/libafl_cc", features = [] }

mimalloc = { version = "0.1" }

clap = { version = "4.1", features = ["derive"] }
dotenv = { version = "0.15" }

serde = { version = "1.0" }
serde_repr = { version = "0.1" }
serde_json = { version = "1.0" }
postcard = { version = "1.0" }

typed-builder = { version = "0.10" }

ahash = { version = "0.7" }
hashbrown = { version = "0.12" }

tokio = { version = "1.24", features = ["full"] }
