[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "stcfuzz"
version = "1.0.0"
description = "Driver for rust fuzzer"
readme = "README.md"
dependencies = ["psutil", "toml"]
requires-python = ">=3.8"

[project.scripts]
stcfuzz = "stcfuzz.driver:main"